namespace: student-api 

application:
  dep:
    replicas: 2
    image:
      name: dev06/one2n-sre-bootcamp
      tag: rest-api
    name: api-server-dep
    ports:
      containerPort: 5000
  svc:
    name: api-server-svc
    ports:
      port: 5000
      targetPort: 5000
  cm:
    name: api-server-config


database:
  statefulset:
    image:
      name: mysql
      tag: 5.7
    name: mysql
    ports:
      containerPort: 3306
    volumeClaimTemplates:
      name: mysql-persistent-storage
      storageSize: 5Gi
  svc:
    name: db
    ports:
      port: 3306
      targetPort: 3306

