apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  namespace: student-api
data:
  DATABASE_HOST: db
  DATABASE_NAME: studentdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: student-api
spec:
  selector:
    matchLabels:
      app: api-server-dep
  template:
    metadata:
      labels:
        app: api-server-dep
    spec:
      containers:
      - name: api-server-dep
        image: dev06/one2n-sre-bootcamp:rest-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: api-server-config
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: databse-creds
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databse-creds
              key: password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: api-server-config
              key: DATABASE_NAME
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "application"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  namespace: student-api
spec:
  selector:
    app: api-server-dep
  ports:
  - port: 5000
    targetPort: 5000

