apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: student-api
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: databse-creds
    creationPolicy: Owner 
  data: 
    - secretKey: password
      remoteRef:
        key: data/mysql/student-api
        property: password
    - secretKey: username
      remoteRef:
        key: data/mysql/student-api
        property: username