#Node-A
apiVersion: v1
kind: Node
metadata:
  name: on2n-sre-bootcamp
spec:
  taints:
    - key: type
      value: application
      effect: PreferNoSchedule
---
#Node-B
apiVersion: v1
kind: Node
metadata:
  name: on2n-sre-bootcamp-m02
spec:
  taints:
    - key: type
      value: dependent_services
      effect: PreferNoSchedule
---
#Node-C
apiVersion: v1
kind: Node
metadata:
  name: on2n-sre-bootcamp-m03
spec:
  taints:
    - key: type
      value: observability
      effect: PreferNoSchedule