version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-1
      - api-2
    
  api-1:
    image: dev06/one2n-sre-bootcamp:rest-api 
    restart: always
    ports:
      - "8081:5000"
    depends_on:
      - db

  api-2:
    image: dev06/one2n-sre-bootcamp:rest-api #python:3.9
    restart: always
    ports:
      - "8082:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'studentdb'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data:
