apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring-ns
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9115"
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "application"
          effect: "PreferNoSchedule"
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:latest
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring-ns
data:
  blackbox.yml: |
    modules:
      http_endpoint:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200, 204]
          no_follow_redirects: false
          preferred_ip_protocol: "ip4"
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring-ns
  labels:
    app: blackbox-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9115"
spec:
  ports:
    - port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter
  type: ClusterIP
