name: CI Pipeline

on:
  push:
    paths:
      - 'milestone-4/**'
  pull_request:
    paths:
      - 'milestone-4/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'

      - name: Change to milestone-4 directory
        run: cd ${{ github.workspace }}/milestone-4
        working-directory: ${{ github.workspace }}/milestone-4
      
      - name: Checking the PWD
        run: echo "${{ github.workspace }}"
        
      - name: Install dependencies
        run: make install

      - name: Lint code
        run: make lint

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: make build_image

      - name: Push Docker image
        run: make push_image
