name: CI Pipeline

on:
  push:
    paths:
      - 'milestone-4/**'
  pull_request:
    paths:
      - 'milestone-4/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: |
      #     cd milestone-4
      #     make install

      - name: Lint code
        run: |
          cd milestone-4
          make lint

      - name: Set build tag
        id: vars
        run: echo "BUILD_TAG=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd milestone-4
          docker build -t dev06/one2n-sre-bootcamp:${{ env.BUILD_TAG }} .

      - name: Push Docker image
        run: |
          cd milestone-4
          docker push dev06/one2n-sre-bootcamp:${{ env.BUILD_TAG }}

      - name: Update application image tag in values.yml
        run: |
          cd milestone-8/application-stack
          yq e '.application.dep.image.tag = strenv(BUILD_TAG)' -i values.yaml

      - name: Commit and push updated values.yml
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          cd milestone-8/application-stack
          git add values.yaml
          git commit -m "Update application Docker image tag to ${{ env.BUILD_TAG }}"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/devanshu06/one2n-sre-bootcamp
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
